### ISSUE TITLE
Liferay 7.1 GA2/3

### ISSUE THREAD

**Issue by jlafuenteribera** [amusarra/liferay-portal-database-all-in-one-support#1]
Hi im trying to use your module for giving Oracle support to my liferay. But GA2/3 versions are not supported.

What can I do to modify your module to make it support that versions.

Thank you.

**Comment by amusarra** [comment]
Hi @jlafuenteribera 
The latest version of the module is certainly compatible with Liferay 7.1 GA1. I have not had time to take a test with GA2 or GA3 but I do not think there should be any difference compared to GA1. Can you tell me the error you get?

**Comment by jlafuenteribera** [comment]
I got it, 

the only thing i had to change is in your pom.xml:

    <liferay.portal.impl.version>3.0.0</liferay.portal.impl.version>
    <liferay.portal.kernel.version>3.0.0</liferay.portal.kernel.version>
    <liferay.petra.lang>2.0.5</liferay.petra.lang>

TO:

    <liferay.portal.impl.version>3.22.20</liferay.portal.impl.version>
    <liferay.portal.kernel.version>3.39.2</liferay.portal.kernel.version>
    <liferay.petra.lang>2.0.7</liferay.petra.lang>

And it work on GA2 perfectly.

Thx for your answer.

**Comment by jlafuenteribera** [comment]
For GA3, we need 

<liferay.portal.impl.version>4.0.0</liferay.portal.impl.version>
<liferay.portal.kernel.version>4.0.0</liferay.portal.kernel.version>

But they havent uploaded that versions to maven repo, so i think its not possible yet, we will have to wait.

**Comment by amusarra** [comment]
For GA3 shuold be:

com.liferay.portal.impl=3.26.4
com.liferay.portal.kernel=3.46.2
com.liferay.petra.lang=2.0.8

Now I will see to release the driver for the GA3 and GA4 versions.

**Comment by amusarra** [comment]
I'm glad you found this driver for Oracle useful.

**Comment by amusarra** [comment]
Hi @jlafuenteribera 
I released version 1.1.1 of the driver for Liferay 7.1 GA2 on Maven [liferay-portal-database-all-in-one-support](https://search.maven.org/artifact/it.dontesta.labs.liferay.portal.db/liferay-portal-database-all-in-one-support/1.1.1/jar)

**Comment by amusarra** [comment]
Hi @jlafuenteribera let me know if I can close the ticket.

**Comment by jlafuenteribera** [comment]
Hi, really thank you.

You can close it sure.

**Comment by rabongo77** [comment]
Hey,

I have followed the steps in this issue and even used the new drivers but I am still having issues.
I am using liferay CE 7.1.2 GA3.

I have attached the relevant section of the error log.

Can you assist.

The error lo
[liferay.2019-02-05.log](https://github.com/amusarra/liferay-portal-database-all-in-one-support/files/2830445/liferay.2019-02-05.log)

**Comment by amusarra** [comment]
Hi.
Which version of SQL SERVER?
The supported version is SQL Server 2016 https://web.liferay.com/documents/14/21598941/Liferay+DXP+7.1+Compatibility+Matrix/9f9c917a-c620-427b-865d-5c4b4a00be85

**Comment by rabongo77** [comment]
It is SQL 2012, I will upgrade the database and give it another shot.

Thanx for the reply
